version: '3.8'
name: caching_server
services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: document_backend
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/configs/config.json
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: document_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: docs_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
